# Generated by Django 2.2.6 on 2019-10-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_fname', models.CharField(max_length=200)),
                ('guest_lname', models.CharField(max_length=200)),
                ('guest_nickname', models.CharField(max_length=200)),
                ('guest_date', models.DateTimeField(verbose_name='Date login')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_fname', models.CharField(max_length=200)),
                ('officer_lname', models.CharField(max_length=200)),
            ],
        ),
    ]
