# Generated by Django 2.2.6 on 2019-10-23 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPPLICATION', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='guest_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 23, 11, 26, 37, 353040), verbose_name='Date login'),
        ),
    ]
