# Generated by Django 2.2.6 on 2019-10-23 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPPLICATION', '0002_auto_20191023_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='guest_email',
            field=models.EmailField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='guest_officer',
            field=models.CharField(default='timi', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 23, 12, 6, 15, 436737), verbose_name='Date login'),
        ),
    ]
