# Generated by Django 2.2.6 on 2019-10-23 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPPLICATION', '0006_auto_20191023_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='guest_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 23, 12, 11, 55, 924349), verbose_name='Date login'),
        ),
    ]
