# Generated by Django 2.2.6 on 2019-10-23 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPPLICATION', '0007_auto_20191023_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='officer_email',
            field=models.EmailField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officer',
            name='officer_phone',
            field=models.CharField(default=23432, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 23, 12, 41, 1, 796626), verbose_name='Date login'),
        ),
    ]
