# Generated by Django 2.2.6 on 2019-10-23 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPPLICATION', '0011_auto_20191023_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='guest_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 23, 12, 44, 45, 248220), verbose_name='Date login'),
        ),
    ]
